language: cpp
matrix:
  include:
    -os: linux
before_install:
  - sudo apt-get update -y
  - sudo apt-get install clang ninja-build -y
script:
  - wget -c --progress=bar https://github.com/llvm/llvm-project/archive/llvmorg-7.1.0.tar.gz
  - tar -xf llvmorg-7.1.0.tar.gz
  - mkdir build
  - pushd build
  - cmake ../llvm-project-llvmorg-7.1.0/llvm -G "Ninja" -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE="Release"
  - ninja clang-format
  - popd
notifications:
  email:
    - denisacostaq@gmail.com
before_deploy:
  - cp -r ./build/bin/clang-format clang-format-$(uname -s)-$(dpkg --print-architecture)
deploy:
  provider: releases
  api_key:
    secure: I9Vk+5XNtK99kWgg/A3/DsSazVbyjQGoCtcLIl1mhVEfjkNVDwWtae+DykTwXCBpF/ctUk26+0f8ZL3lUYcCsdvnDkJod/P//im8FyNC1hYWVz0f9pTl7At92rpU2qoDMTYb/b3hQfUxVnyd3B+maresQN7+RZNbwLNEedGJHW0STRP8MlWiRGYvXqd1EQWB5Lfs/5wc60dm3tOGVhfWbpYkSsx4WKQfDdX+AI7Y1SVlZxYDLONl4j44qIr+XyhUuS1h+p8kn5/FwOsapwapMG4IyESoHNr5OWGyTFqAZh7CndEAes6JpwtT0BMOWfCzl4h6nL/Sz4iKvUGl96MSDEG8dREfyJ9ibxU/Z7ZeAPTy+b3MozGDH7WHwYaCAjz4gZuJyaU7Lyn8CX1Rs+5wUVuKWdN8bg8s91q4ogxILK+V4gQ2i4jzHnXCNVV70a4AmOp6olMTavVAQSI5w5kBU3AIweBKOqNn2plL036mYzWbV/1kJ42BSwjQORCnL4JJIUWAapBLBNDyvdVqT4xi4rs7zOu2jY8l46BUm4okYmXisA5Luu9L5zxPak3/IBiLztbIWh7NdEu/g9HmfHo3vMYVSzBkWbhEfgQoABcAUkX0Yhp9Hfe9TXt/2R5hsKTydX43rnveA2swi9+e/QsXbqLT5fMiQJKEwJT9b+1TmWE=
  file:
   - clang-format-$(uname -s)-$(dpkg --print-architecture)
  skip_cleanup: true
  draft: true
  on:
    repo: clang-format-binary-releases
    tags: true
